### ISSUE TITLE
Space character in path will cause sdk download failure

### ISSUE THREAD

**Issue by filod** [spatialos/UnityGDK#387]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

#### Description
can not retrieve worker sdk when starter kit in a path which have space in folder name.

## Expected behaviour
retrieve worker

## Current behaviour

only a tip from unity log: "Failed to download SpatialOS Core Sdk version XXX..." 

## Possible solution

1. make target saving path encoding right 
2. suggestion: more readable error msg from process output (i can't see any stdout msg form unity's console, this make my debugging so hard)

## Steps to reproduce

download the starterkit in a path with space in it (like `D:\game dev`), then open unity editor. 

## Environment
windows 10

**Comment by samiwh** [comment]
Thanks for raising this @filod. A ticket has been raised and this should be fixed soon.

**Comment by samiwh** [comment]
Hi @filod, which GDK commit do you have checked out?

**Comment by filod** [comment]
i checked GDK from git releases tab here
https://github.com/spatialos/UnityGDK/releases/tag/starter-project

**Comment by samiwh** [comment]
It seems like the directory name issue was fixed after that tag. Currently we don't have a proper release process are using the branch `pinned/starter-project` for use with other projects, or just use `master`. We will probably remove that tag as it isn't really a release :\.

For the client zip issue, did you build the client worker before uploading the assembly? It should create an artifact called `UnityClient@Windows.zip`.

**Comment by samiwh** [comment]
Generally the SpatialOS forums are the best place to raise errors; they are more easily searchable for others having the same problem. However we will deal with issues raised here too :).
